### ISSUE TITLE
monitor scaling causes oGDI.MeasureString() to return incorrect value

### ISSUE THREAD

**Issue by NigelGomm** [DougHennig/Ribbon#24] opened 2023-12-14 23:29 UTC
i suspect it's the hard coding of cnFACTOR ?

for now i have replaced the call on .measurestring() and subsequent use of .nwidth in my copy with variations on
`TXTWIDTH(THIS.CAPTION,THIS.lblbutton.FONTNAME,THIS.lblbutton.FONTSIZE) * FONTMETRIC(6,THIS.lblbutton.FONTNAME,THIS.lblbutton.FONTSIZE)`
and that seems to be working in testing so far.

I can post my new versions of .calculatewidth() for sfribbontoolbarbutton, sfribbontoolbarbuttonhorizontal and sfribbontab but suspect you'd prefer a gdi solution?

n

**Comment by DougHennig** [comment] 2023-12-16 13:06
I need more information to be able to look into this: steps to reproduce, screen shot of what it looks like, etc.

**Comment by NigelGomm** [comment] 2023-12-18 15:46
(Part of the problem is that things are exacerbated by my dpiawaremanager code increasing widths and fontsizes by 1.75.)

Just change monitor scaling in your windows control panel settings to 175%

![image](https://github.com/DougHennig/Ribbon/assets/87875272/cc12adf0-b9ac-46ee-b757-115ef3e0650d)


This is with your original .calculatewidth() in place with no monitor scaling
![image](https://github.com/DougHennig/Ribbon/assets/87875272/1c54e245-00ad-41ce-83bc-a0cd0d293165)


This is same but with monitor scaling at 175% (and my dpiawaremanager switched off so no change to widths or fontsizes)
![image](https://github.com/DougHennig/Ribbon/assets/87875272/8051ca33-f233-4040-8758-de451177e276)



now here it is at 175% with my txtwidth*fontmetric code. (still with my dpiawaremanager switched off)
![image](https://github.com/DougHennig/Ribbon/assets/87875272/fcfac948-5e05-4c93-9960-76b28ac45946)

and again but with dpiawaremanager code on.
![image](https://github.com/DougHennig/Ribbon/assets/87875272/87a87e84-bb71-45c5-94e1-761b359a9eb5)


n

**Comment by NigelGomm** [comment] 2023-12-18 16:22
and using oGDI.measurestring() with my dpiawaremanager increasing widths and fonts by 1.75 does this

![image](https://github.com/DougHennig/Ribbon/assets/87875272/eba3e8d1-9804-4adc-80d9-672523e2608d)


n

**Comment by DougHennig** [comment] 2023-12-23 14:21
I can't reproduce that. Here's a ribbon on a monitor at 3840x2160, 125%:

![125](https://github.com/DougHennig/Ribbon/assets/12052409/3445781c-49c8-4a69-9c3f-e6b7b1a9ad13)

Here it is at 175%:

![175](https://github.com/DougHennig/Ribbon/assets/12052409/e446c803-955b-4cd6-98db-344de18bed54)

**Comment by DougHennig** [comment] 2023-12-23 14:55
I was able to reproduce it by creating a DPI-aware manifest file and running from an EXE. I'll see what I can do about it.

**Comment by DougHennig** [comment] 2023-12-23 16:41
This is fixed in the latest build.

**Closed by DougHennig** 2023-12-23 16:41 UTC

**Comment by NigelGomm** [comment] 2023-12-24 11:14
sorry... i'd forgotten about the manifest.nOn Dec 23, 2023 5:41 PM, Doug Hennig ***@***.***> wrote:
This is fixed in the latest build.
